applications:

    main:
        stack:
          - "python@3.11"
        source:
            root: main
        hooks:
            build: |
                set -eux
                pip install -r requirements.txt   
        relationships:
            elasticsearch:
            
            # headlesschrome: 'headlesschrome:http'
            # influxdb: 'influxdb18:influxdb'
            # kafka: 'kafka25:kafka'
            # memcached: 'memcached16:memcached'
            # mongodb: 'mongodb36:mongodb'
            # opensearch: 'opensearch12:opensearch'
            # oraclemysql: 'oraclemysql:mysql'
            # mysql: 'mariadb104:mysql'
            # postgresql: 'postgresql12:postgresql'
            # rabbitmq: 'rabbitmq39:rabbitmq'
            # redis: 'redis6:redis'
            # solr: 'solr86:solr'
            # vault-kms: 'vault-kms:sign'
        web:
            commands:
                start: uvicorn main:app --port $PORT

services:

    elasticsearch:
        type: elasticsearch:7.10

    # headlesschrome:
    #     type: chrome-headless:120

    # influxdb:
    #     type: influxdb:2.7

    # kafka25:
    #     type: kafka:3.2

    # mariadb:
    #     type: mariadb:11.2

    # memcached:
    #     type: memcached:1.6

    # mongodb:
    #     type: mongodb:4.0

    # networkstorage:
    #     type: network-storage:2.0

    # opensearch:
    #     type: opensearch:2

    # oraclemysql:
    #     type: oracle-mysql:8.0

    # postgresql:
    #     type: postgresql:16

    # rabbitmq:
    #     type: rabbitmq:3.12

    # redis:
    #     type: redis:72
    #     size: S

    # solr:
    #     type: solr:9.2
    #     disk: 256
    #     configuration:
    #         cores:
    #             maincore:
    #                 conf_dir: !archive "solr-config"
    #         endpoints:
    #             solr:
    #                 core: maincore
    # vault-kms:
    #     type: vault-kms:1.12
    #     configuration:
    #         endpoints:
    #             sign:
    #                 - policy: admin
    #                   key: vault-sign
    #                   type: sign
    #                 - policy: sign
    #                   key: vault-sign
    #                   type: sign
    #                 - policy: verify
    #                   key: vault-sign
    #                   type: sign


routes:

    "https://{default}/":
        id: main
        type: upstream
        upstream: "main:http"
        cache:
            enabled: true
            cookies: []
            default_ttl: 300

    # "https://{default}/php":
    #     id: php
    #     type: upstream
    #     upstream: "php:http"

    # "https://{default}/nodejs":
    #     id: nodejs
    #     type: upstream
    #     upstream: "nodejs:http"

    # "https://{default}/python":
    #     id: python
    #     type: upstream
    #     upstream: "python:http"

    # "https://{default}/java":
    #     id: java
    #     type: upstream
    #     upstream: "java:http"

    # "https://{default}/golang":
    #     id: golang
    #     type: upstream
    #     upstream: "golang:http"
