applications:

    main:
        # type: python:3.11
        stack:
          - "python@3.11"
          - "python311Packages.pip"
        # build:
        #     flavor: none
        source:
            root: main
        hooks:
            build: |
                # Fail the build if any errors occur
                set -eux

                # # Download the latest version of pip
                # python -m pip install --upgrade pip

                # Install dependencies
                pip install -r requirements.txt   
        relationships:
            elasticsearch: 'elasticsearch:elasticsearch'
            # headlesschrome: 'headlesschrome:http'
            # influxdb: 'influxdb18:influxdb'
            # kafka: 'kafka25:kafka'
            # memcached: 'memcached16:memcached'
            # mongodb: 'mongodb36:mongodb'
            # opensearch: 'opensearch12:opensearch'
            # oraclemysql: 'oraclemysql:mysql'
            # mysql: 'mariadb104:mysql'
            # postgresql: 'postgresql12:postgresql'
            # rabbitmq: 'rabbitmq39:rabbitmq'
            # redis: 'redis6:redis'
            # solr: 'solr86:solr'
            # vault-kms: 'vault-kms:sign'



        # The configuration of app when it is exposed to the web.
        web:
            commands:
                start: uvicorn main:app --port $PORT
            # locations:
            #     "/":
            #         root: 'web'
            #         index: ['index.html']
            #     "/relationships":
            #         # The public directory of the app, relative to its root.
            #         root: "relationships/web"
            #         # The front-controller script to send non-static requests to.
            #         passthru: "/relationships/index.php"

# crons:
#     renewcert:
#         # Force a redeploy at 10 am (UTC) on the 1st and 15th of every month.
#         spec: '0 10 1,15 * *'
#         cmd: |
#             if [ "$PLATFORM_BRANCH" = master ]; then
#                 platform redeploy --yes --no-wait
#             fi

# mounts:
#     networkstorage:
#         source: service
#         service: networkstorage
#         source_path: networkstorage


services:

    elasticsearch:
        type: elasticsearch:7.10

    # headlesschrome:
    #     type: chrome-headless:120

    # influxdb:
    #     type: influxdb:2.7

    # kafka25:
    #     type: kafka:3.2

    # mariadb:
    #     type: mariadb:11.2

    # memcached:
    #     type: memcached:1.6

    # mongodb:
    #     type: mongodb:4.0

    # networkstorage:
    #     type: network-storage:2.0

    # opensearch:
    #     type: opensearch:2

    # oraclemysql:
    #     type: oracle-mysql:8.0

    # postgresql:
    #     type: postgresql:16

    # rabbitmq:
    #     type: rabbitmq:3.12

    # redis:
    #     type: redis:72
    #     size: S

    # solr:
    #     type: solr:9.2
    #     disk: 256
    #     configuration:
    #         cores:
    #             maincore:
    #                 conf_dir: !archive "solr-config"
    #         endpoints:
    #             solr:
    #                 core: maincore
    # vault-kms:
    #     type: vault-kms:1.12
    #     configuration:
    #         endpoints:
    #             sign:
    #                 - policy: admin
    #                   key: vault-sign
    #                   type: sign
    #                 - policy: sign
    #                   key: vault-sign
    #                   type: sign
    #                 - policy: verify
    #                   key: vault-sign
    #                   type: sign


routes:

    "https://{default}/":
        id: main
        type: upstream
        upstream: "main:http"
        cache:
            enabled: true
            cookies: []
            default_ttl: 300

    # "https://{default}/php":
    #     id: php
    #     type: upstream
    #     upstream: "php:http"

    # "https://{default}/nodejs":
    #     id: nodejs
    #     type: upstream
    #     upstream: "nodejs:http"

    # "https://{default}/python":
    #     id: python
    #     type: upstream
    #     upstream: "python:http"

    # "https://{default}/java":
    #     id: java
    #     type: upstream
    #     upstream: "java:http"

    # "https://{default}/golang":
    #     id: golang
    #     type: upstream
    #     upstream: "golang:http"
